# Directory for end-to-end tests of Sanity.
# Individual unit tests are embedded next to the individual source files they test.

# Needed for use in the test_sanity_prog() BUILD macro.
exports_files(["tester.py"])
