# Standard library for Sanity-compiled code.

package(default_visibility = ["//:__subpackages__"])

cc_library(
    name = "input",
    srcs = ["input.c"],
)

cc_library(
    name = "stringify",
    srcs = ["stringify.c"],
)